### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Joltrix** [StarcounterApps/Timeline#1]
- [ ] Use with Simplified.Ring6.EventParticipation
- [ ] Make timeline "workable" with the people app. -> Use blending
- [ ] Event sorting ( "different views" ) - Display all events of type NotesEvent
